apiVersion: v1
kind: Service
metadata:
  name: smaster
  labels:
    app: smaster
spec:
  clusterIP: None
  selector:
    app: smaster
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: smaster
spec:
  replicas: 1
  selector:
    matchLabels:
      name: smaster
  serviceName: smaster
  template:
    metadata:
      labels:
        name: smaster
    spec:
      containers:
      - name: smaster
        image: bbinet/salt-master
---
apiVersion: v1
kind: Service
metadata:
  name: sminion
  labels:
    app: sminion
spec:
  clusterIP: None
  selector:
    app: sminion
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sminion
spec:
  replicas: 3
  selector:
    matchLabels:
      name: sminion
  serviceName: sminion
  template:
    metadata:
      labels:
        name: sminion
    spec:
      containers:
      - name: sminion
        image: bbinet/salt-minion
