apiVersion: v1
kind: Service
metadata: 
  name: filehost-web
spec: 
  ports: 
     -  port: 12002
        protocol: TCP
        targetPort: 80
        nodePort: 32002
  selector: 
    app: filehost
  type: NodePort
