apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-client-volume
  labels:
    app: vault-client-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi