apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultclient
  labels:
    app: vaultclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultclient
  template:
    metadata:
      labels:
        app: vaultclient
    spec:
      volumes:
      - name: vault-client-volume
        persistentVolumeClaim:
          claimName: vault-client-volume
      containers:
      - name: vaultclient
        image: localhost:32000/oleksiimy/vault_client:0.1
        volumeMounts:
        - name: vault-client-volume
          mountPath: /mount
        

