apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultchallenge2
  labels:
    app: vaultchallenge2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultchallenge2
  template:
    metadata:
      labels:
        app: vaultchallenge2
    spec:
      containers:
      - name: vaultchallenge2
        image: localhost:32000/oleksiimy/vault_challenge2:0.1
        command: [ "/bin/sh", "-c", "sh /opt/setup.sh && tail -f /dev/null" ]
        

