apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultchallenge1
  labels:
    app: vaultchallenge1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultchallenge1
  template:
    metadata:
      labels:
        app: vaultchallenge1
    spec:
      containers:
      - name: vaultchallenge1
        image: localhost:32000/oleksiimy/vault_challenge1:0.1
        command: [ "/bin/sh", "-c", "sh /opt/setup.sh && tail -f /dev/null" ]
        

