apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultchallenge3
  labels:
    app: vaultchallenge3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultchallenge3
  template:
    metadata:
      labels:
        app: vaultchallenge3
    spec:
      volumes:
      - name: vault-client-volume
        persistentVolumeClaim:
          claimName: vault-client-volume
      containers:
      - name: vaultchallenge3
        image: localhost:32000/oleksiimy/vault_challenge3:0.1
        command: [ "/bin/sh", "-c", "sh /opt/setup.sh && tail -f /dev/null" ]
        volumeMounts:
        - name: vault-client-volume
          mountPath: /mount

