apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultserver
  labels:
    app: vaultserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultserver
  template:
    metadata:
      labels:
        app: vaultserver
    spec:
      containers:
      - name: vaultserver
        image: localhost:32000/oleksiimy/vault_server:0.1
        

